name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.16, 1.15]
    name: Test with Go version ${{ matrix.go }}
    steps:
      - uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.7.0

      - name: Get dependencies
        run: go mod download

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test -v

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.7.0
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.16

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
