name: test
on:
  push:
    branches:
      - '*'
      - '!dependabot/**'
    tags-ignore:
      - '*'
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.16, 1.15]
    name: Test with Go version ${{ matrix.go }}
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.2

      - name: Get dependencies
        run: go mod download

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test -v
